### ISSUE TITLE
House distribution bar not visible on print

### ISSUE THREAD

**Issue by mainrs** [drallieiv/keyforge-burger-inserts#20]
Hello!

The colored distribution bar is not visible on my print. The colored bar is visible on the website, but when generating the print via `Ctrl+P`, the bars aren't colored anymore.

**Comment by AdrienNguyenWorldline** [comment]
it's a known bug, kind of painfull to fix.
Don't have much time, but I can review the change if someone else what to have a go.

I think u can trick your browser printing options by checking a box about priting background colors which is usually off by default.

**Comment by oOZeVsOo** [comment]
Hello.
The option can be checked or unchecked and the bar's colors won't show up (tried with Chrome and Edge).
Do you have some kind of workaround to enable the printing ?
Thanks you very much.

**Comment by drallieiv** [comment]
@oOZeVsOo 
I just saw I had a bad rule in my css and I should fix that.
After that you should be able to check "Background graphics" option when printing. as in here : https://stackoverflow.com/a/60385700/6512623

**Comment by oOZeVsOo** [comment]
Thank you very much !
I will try this fix as soon as it's published (right now there was a build error in the merge)

**Comment by oOZeVsOo** [comment]
Waiting for the fix, a workaround is:
- Open Chrome console ( Ctrl+Shift+J )
- Run command:
`document.body.innerHTML = document.body.innerHTML.replace(/\);"><\/div>/g, ") !important;\"></div>")`
- Print (you should see the colored bar in the printing preview).
